# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=50)),
                ('useragent', models.CharField(max_length=50)),
                ('url', models.TextField(blank=True, default='', max_length=300)),
                ('datetime', models.DateTimeField()),
                ('millisecond', models.IntegerField()),
                ('session', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=30)),
                ('local_host', models.CharField(max_length=30)),
                ('local_port', models.IntegerField()),
                ('service', models.CharField(max_length=10)),
                ('remote_host', models.CharField(max_length=30)),
                ('remote_port', models.IntegerField()),
                ('data', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
