# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userconfig_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_key',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
