# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160921_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='owner',
        ),
    ]
