# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_nodeowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeowner',
            old_name='owner',
            new_name='user',
        ),
    ]
