# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161006_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='protocol',
            field=models.CharField(max_length=30),
        ),
    ]
